### ISSUE TITLE
feature request: configure ~buf and ~cwd

### ISSUE THREAD

**Issue by cvlmtg** [ncm2/ncm2-path#2]
would it be possible to configure this source to show only paths relative to buffer and/or cwd? I'm basically interested only in paths relative to the buffer, so maybe on a certain file I get the only two ~buf candidates mixed with tens of ~cwd candidates, which just make harder to select the one I want.

Thanks in advance!

**Comment by roxma** [comment]
I've split path completion into three sources, `~buf` has higher priority than others.

If you do want to disable `~cwd`:

```
let g:ncm2_path#cwdpath_source_override = {'enable': 0} 
```
