### ISSUE TITLE
Buffer path source triggers for [a-zA-Z]

### ISSUE THREAD

**Issue by BonaBeavis** [ncm2/ncm2-path#7]
Have file `test.md` in buffer path and type `tes` => `test.md` will appear as a completion.

**Comment by roxma** [comment]
I don't understand. ncm2-path does completes for `tes` => `test.md`

**Comment by BonaBeavis** [comment]
Shouldn't it only trigger when an input starts with `.` or `/`. But I guess this is useful for c with header and source files.

**Comment by roxma** [comment]
> Shouldn't it only trigger when an input starts with . or /

```vim
call ncm2#override_source('bufpath', {'complete_length': -1})
call ncm2#override_source('cwdpath', {'complete_length': -1})
call ncm2#override_source('rootpath', {'complete_length': -1})
```

Read `:help  ncm2#override_source` , `:help  ncm2-complete_length` , and `:help ncm2#register_source-example`
